### ISSUE TITLE
bug : when trying to verify a *.github.io domain, the user is redirected to the wordpress landing

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#138]
Per https://github.com/brave-intl/publishers/issues/50

Screen 4.e. "If *.github.io is used as the domain, they will be given an option similar to the text option from 4.a" 

Currently on https://publishers-staging.basicattentiontoken.org/ the user is redirected to https://publishers-staging.basicattentiontoken.org/publishers/verification_wordpress instead

**Comment by alexwykoff** [comment]
Per lgebhardt, the host inspector needs to be online during testing for this flow to work, otherwise it will default to the wordpress option.

**Comment by nvonpentz** [comment]
Reopening because more users from the community forums have reported being directed to the wordpress verification landing page, when their sites are not using wordpress.

1. https://community.brave.com/t/site-operator-verification-thinks-my-site-is-wordpress/10905
2. https://community.brave.com/t/verification-https-failure/9170
