### ISSUE TITLE
Send out messaging to users who were impacted by Uphold email leak

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1794]
We should notify users who were registered before nov 21 2018 and uphold connected. Letting them know that back in November Uphold exposed their email addresses and that there have been reports of scammers targeting them

**Comment by diracdeltas** [comment]
* link to https://uphold.com/en/blog/a-security-update-from-uphold
* mention that according to Uphold, users who were affected should have gotten an email notification from Uphold
* mention that we are sending out this email because we recently received reports from users that suggest the email database may have been sold to third-parties
