### ISSUE TITLE
Fetch transaction history for statement from channel cards

### ISSUE THREAD

**Issue by evq** [brave-intl/publishers#2057]
This is dependent on https://github.com/brave-intl/publishers/issues/2048 which will include creating a per-channel Uphold card. In order to merge p2p tips into the statements which we provide to users we will need to query uphold for the transaction history of each card.

**Comment by corymcdonald** [comment]
Here's my stream of consciousness on this - 

I'm wondering how we should handle this, given a card we can make a call to the `cards/:id/transactions` endpoint, and we can get a list of transactions (including an ID, and createdAt time).

On Publishers i'm thinking this will mean that we'll have to track a historical record of user cards - because if a user changes their default currency then this will generate all new cards for their channels.

I'm imagining that when Eyeshade makes the request it will include the publisher's id and the last transaction time it's aware of.

Then on publisher's side of things we'll need to get the list of cards that a publisher has, that were active after the last transaction time, then return the list of transactions for each various cards.


I'm also wondering if it's best for Eyeshade to query for this or for Publishers to regularly `POST` to Eyeshade to keep it updated anytime we pull the latest transactions.  Really I feel like it would be ideal if we could use webhooks from Uphold to POST to when a transaction happens, especially for anonymous wallets? So then if a transaction happens on an anonymous wallet that we own then we could add it to the accounting ledger, without having to do all the above work.  

Thoughts?

**Comment by evq** [comment]
As we discussed offline - eyeshade won't be involved in this process. We won't be storing info on the p2p tips there.

Publishers will simply make requests to both Uphold and eyeshade to merge and produce the final statement for presenting to the user

**Comment by corymcdonald** [comment]
This was addressed via https://github.com/brave-intl/publishers/pull/2297
