### ISSUE TITLE
Existing statements should list under "Generate" line

### ISSUE THREAD

**Issue by mrose17** [brave-intl/publishers#208]
if there are any existing statements for the publisher, they should be listed, one-per-line below the "Generate" line.

i suspect that the best way to list them is have the Generation date, the period, and a link to download...

![0](https://user-images.githubusercontent.com/400552/31972018-6c9d6c0a-b8d3-11e7-84e8-f79077c6ad82.png)

**Comment by mrose17** [comment]
ps: i suspect that the "Statement" label should be "Statements" (-;

**Comment by dgeb** [comment]
I wanted to weigh in with my WIP here to provide an opportunity for feedback. Here's how it looks after a very busy day testing statement generation:

![screen shot 2017-10-25 at 5 49 06 pm](https://user-images.githubusercontent.com/29122/32025145-194e20be-b9ad-11e7-910e-55aa086d2f54.png)

I'm not sure the length of the list is of great concern, since this has been a very unusual period with me testing the feature. And we are clearing the statements out after they expire (in 24 hours).

The statements are shown in chronological order, newest at the top.

When `Generate` is clicked, a new row is added to the top, and `Generating...` is displayed in the "Download" column. Once successful, this becomes a `Download` link like the others.

Only one report can be generated at a time. After the report has been generated, the `Generate` link reappears.

**Comment by mrose17** [comment]
this is a great start, but i think the row requires more context, either the date/time is there instead of 'MM-DD' or there are two more columns besides the generation timestamp: the timestamp for the first transaction in the file and the timestamp for the last transaction in the file.

**Comment by dgeb** [comment]
@mrose17 should we attempt to detect the time zone of the user from their browser and display timestamps in that format? How about 24 hour clock vs. am/pm?

**Comment by mrose17** [comment]
i really dislike the whole TZ thing. never makes anyone happy, ok, let's do this: just have the date as "October 26, 2017" and skip the time. that obscures the issue until we can think about it in phase 4.
