### ISSUE TITLE
[object Object] appears during hover of social media icons on landing page

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2687]
https://www.reddit.com/r/BATProject/comments/ggxbc3/note_for_developers_object_object_shows_up_when_i/

**Comment by jonathansampson** [comment]
A user on Twitter just pointed this out to me as well: 
![image](https://user-images.githubusercontent.com/815158/104112397-efc1a100-52b3-11eb-8c5d-f686667d4b6d.png)

**Comment by jonathansampson** [comment]
After taking a quick look at this, I suspect the fix is quite simple:

https://github.com/brave-intl/publishers/blob/f305c9137d7b58725b7c0657c26c0e0ebc6ebb9e/public/creators-landing/src/sections/main-section/sentEmail/index.js#L17

https://github.com/brave-intl/publishers/blob/7f60e665f7374b334b6ffd5fac2ac05254fa7df4/public/creators-landing/src/sections/main-section/sentEmail/index.js#L82-L86

We don't appear to be calling these values from the imported `locale` object. For instance, `sign.iconCommunityTitle` should be `locale.sign.iconCommunityTitle`.

Perhaps @yachtcaptain23 can confirm?
