### ISSUE TITLE
Signup email verification greeting shouldn't guess a name

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#270]
With #261, verification emails don't yet have the user's name so we guess from their email: name@domain.com. frequently name isn't exactly what looks friendly

e.g. if Alice Blogger at BlogLandLLC had an email ablogger@blogland.world it would show as `Hi, ablogger`

we can just do "Hello," without name for the first email.

**Comment by jenn-rhim** [comment]
I totally agree, @ayumi -- in terms of being user friendliness, this is not good enough for those who have obscure username. 

With that said, still it's the best alternative to address people because
- a lot of the username refers to the real name so those cases we will be right.
- people choose their username deliberately (alias, alter-ego :), etc.)
- it also plays as a quick verification of the email being specific to you, rather than mass-, generic email that may not be relevant if we just say hi.

In the previous study, users aren't taking this as objectionable.

Weighing pros and cons, it's still a better alternative to extract the username. :)

**Comment by ayumi** [comment]
@jenn-rhim all right, we can revisit this if users comment on it
