### ISSUE TITLE
Expired key screen should be better handled

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#304]
1. the message is tucked away that I doubt user sees it
2. the message is not user friendly

Likely they'd be puzzled as to what happened as they just returned to the same screen before clicking verify email link.

![screen shot 2017-11-16 at 10 38 53 pm](https://user-images.githubusercontent.com/4369856/32964641-b9bcf6c8-cb88-11e7-989f-18498348c6ec.png)

**Comment by nvonpentz** [comment]
@jenn-rhim do you suggest we create a new view for new publishers who attempt to verify with an expired token, or do you think a more clear message will suffice?

I think something like "Your verification token has expired.  Please enter your email address and click 'Get Started' to begin again." should be enough.

**Comment by jenn-rhim** [comment]
Not on the landing page. We need a new page for 'expired key' with the message right above the email field.  This page is for catching **all cases** of expired access key, sign up + log in.


![login-new-key](https://user-images.githubusercontent.com/4369856/33057018-80edbe38-ce3d-11e7-92d8-34e727b937ca.png)

**Comment by lgebhardt** [comment]
Publishers are not uniquely identified by email. Currently we need to ask for either the domain or have them authenticated with oauth (as per the existing login screen). Until we separate the owners from the publishers the flow described here (using only email to login) will not support either of the existing login paths (domain and google oauth).

The flow of returning a publisher with an expired session to the login page is certainly an improvement. So is moving the flash message into the body. Rather than wait until the data model has been reworked could we put the blue flash and new wording on the existing login page?

**Comment by mrose17** [comment]
@lgebhardt - the question is how many cycles it will take for the quick fix. if it's more than an hour or so, it's better to wait for the comprehensive fix.

**Comment by nvonpentz** [comment]
As @lgebhardt described to me, we have two options:
1. Wait until the new account model is finished, then do a comprehensive fix.
2. Take the publisher back to the log-in page, adding the revamped flash to the login page to cut down on confusion.

If we choose 2, I can have this done by tomorrow - but need confirmation from @jenn-rhim and @mrose17 that this is what we want to do.  Otherwise I will remove the 'urg' tag.

**Comment by nvonpentz** [comment]
We will hold off on this until the new account model is established.  This will be covered in #273 or shortly after #273 is resolved.
