### ISSUE TITLE
Determine solution for growing js code

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#348]
As @dgeb noted in #342, we are in need of a solution to better manage the javascripts.
> I think we're getting to a level of dynamism on the frontend where we should consider introducing a framework such as Glimmer or Ember to replace the vanilla JS. I'm getting uncomfortable with the lack of module management for JS and the use of globals. We also need to improve the testing of the growing JS codebase.

**Problems**
- Lack of module management
- Shared global variables across unrelated scripts
- Lack of consistent javascript testing

**Proposed solutions**

I will update this post as we expand on the problems and discuss potential solutions.

**Comment by mixonic** [comment]
Currently the codebase uses Rails 5 + Sprockets + Uglify gem + UglifyJS v1 for production asset compilation. Unfortunately UglifyJS v1 is not compatible with modern post-ES5 JavaScript (`let`, `() => {}` functions etc).

We explored three options to resolve this, and found neither to be trivial:

* There is a flag `harmony: true` which can be passed to the Uglify gem. This enables experimental ES6 support, however it does this by leveraging an unsupported and deprecated JavaScript library. This does not sound like a good way to move forward.
* Sprockets can potentially use babel as a compilation step, and once in Babel we could use [babel-minify](https://github.com/babel/minify) to do minification instead of uglify. I'm unsure if any versioning issues exist here (what version of babel will sprockets be happy with, what version does babel-minify require).
* Adopt the "happy path" for Rails, the [webpacker](https://github.com/rails/webpacker) gem. Unfortunately this means migrating away from the Sprockets build pipeline and related features (like importing a file with a comment). This is probably the best direction to head for build pipeline stability if we wanted to continue adding JS to the Rails app directly.

**Comment by ayumi** [comment]
I discussed briefly with @dgeb on how to handle JS here, and I think I'd prefer to go with the minimal Vanilla JS strategy.

So the last suggestion above on "happy path" webpacker gem, this sounds appealing to me. I think Webpack is cool also.

**Comment by mixonic** [comment]
@ayumi Can you say more about "minimal Vanilla JS strategy"? I'm not sure what you mean. "Vanilla JS" would probably mean dropping Sprockets, which we currently use. I think we should keep using a minification solution (like uglify v2) as well.

Yeah webpacker isn't trivial to adopt but it is the Railsy happy path. I think it would an improvement over the current sprockets system.

**Comment by ayumi** [comment]
@mixonic sorry, by "Vanilla JS" I meant not using any framework.

Agree on minification.

A related thing is, we're working on a shared Brave UI kit, which is currently some React components: https://github.com/brave/brave-ui
We might try in the medium future to put parts of this into Publishers. I don't think we'd want to rewrite substantial parts of the app, but it could be nice to add styles or buttons for limited bits (like some JS heavy forms).

At the moment however I'm satisfied. We'd like to focus on feature work, making sure to put in Capybara tests to cover JS logic. I think we can get away with ES5 for now.

To track an eventual refactor to webpacker: #422

(As an aside: I browse most of the web without scripts and try to keep sites I work on minimal on JS on principle. But happy UX is important too.)
