### ISSUE TITLE
[WIP] Email - Threshold met for YouTube Channel

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#372]
**Conditions :** 
A channel exists which has acquired $10 worth of BAT and has thus far not started verification.

**Frequency :** 
Monthly until verification is complete.

**Subject :** 
 Money is waiting for <_YouTube channel_>, verify your channel with Brave to claim your funds!

**Body :** 

Salutation : 
Hi <_username_>!

Paragraph : 
Your channel has accumulated quite a bit and we’d love to hand it over.    Please visit https://publishers.basicattentiontoken.org/ to start the verification process.  There are no fees, no gimmicks, we just want you to get paid and keep making awesome content.

Call-to-Action Button Text : 
Verify My Channel

Post-script : 
Got questions? Visit https://basicattentiontoken.org/ to learn more about how the micropayments work.

We look forward to having you join the thousands of domains and YouTube channels already receiving funds from their audience.

**Comment by alexwykoff** [comment]
Suggestions to copy changes are welcome

**Comment by ayumi** [comment]
Youtube (and other providers) may not allow people to determine channel email addresses, as this could be used for abuse.
At least there's a "Contact channel owner" feature which I've used.

Let's determine if it's possible to contact channel owners programmatically.

Related: #375

**Comment by alexwykoff** [comment]
@nvonpentz using https://www.youtube.com/user/alexwykoff as an example, it may be significantly difficult to reach out to YouTube creators in this manner.  We may need to scuttle the email approach and look toward an alternative route.

**Comment by nvonpentz** [comment]
@ayumi  @alexwykoff I’ve done some research and it doesn’t look like there is any reliable way to find an email address for an an arbitrary youtube channel.  Here are the methods I’ve investigated

1. Lookup email with Youtube Data API - impossible without read access
2. Send a DM on youtube instead of email - impossible, this feature of the youtube API has been deprecated.  <sup>[1](https://stackoverflow.com/questions/35375405/send-a-message-to-a-youtube-channel-via-api)</sup> <sup>[2](https://www.quora.com/Sending-private-messages-using-YouTube-API-V3-is-not-implemented-and-at-the-same-time-this-feature-in-the-old-API-is-not-working-anymore-Will-Google-support-this-feature-in-the-new-API-in-the-future-or-not)</sup>
3. Scrape emails from youtube channel description - possible but inconsistent.  Many youtubers include their email somewhere in their channel description.  We could scrape this programmatically, but there is no guarantee that it will be there, or that it is the correct destination for the notification email.
4. Look up channel email addresses manually.  On the channel under 'About' in the 'Details' section, you can fill out a captcha and it will give the business contact information for the channel.  We could manually go through the channels that have reached the threshold and compile a list of email addresses send the notifications too.  This might be viable now, but it is not viable at scale.

I think the best course of action would be a combination of 3 & 4.  We could get a percentage of email addresses of unverified channels by scraping channel descriptions.  This percentage would stay about the same as we scale.  We would also produce a list of the 20 or so unverified channels that have the most funds waiting, and manually get their email address by filling in the captcha.

With this approach, we always are contacting some percentage of unverified channels, as well as the 20 with the most funds waiting.

We might also want to encourage users who donate to reach out to the channels who they’ve donated to when they donate.

Does anyone have another suggestion?

**Comment by lgebhardt** [comment]
Make a comment on the most recent video as a fall back if 3&4 fail?

**Comment by nvonpentz** [comment]
@lgebhardt It looks like we can do that programmatically, although the number of comments we can make will be restricted.  We can also leave a comment on their channel if they have enabled the 'Discussion' tab, although this doesn't appear to be widely used.

https://developers.google.com/youtube/v3/docs/commentThreads/insert#auth

**Comment by corymcdonald** [comment]
Closing as not applicable
