### ISSUE TITLE
[WIP] Email - Threshold met for site operator

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#375]
**Conditions :** 
A domain exists which has acquired $10 worth of BAT and has thus far not started verification.

**Frequency :** 
Monthly until verification is complete.

**Subject :** 
 Money is waiting for <_domain_>, verify your site with Brave to claim your funds!

**Body :** 

Salutation : 
Hi!

Paragraph : 
Your site has accumulated quite a bit of fundage and we’d love to hand it over.    Please visit https://publishers.basicattentiontoken.org/ to start the verification process.  There are no fees, no gimmicks, we just want you to get paid and keep making awesome content.

Call-to-Action Button Text : 
Verify My Site

Post-script : 
Got questions? Visit https://basicattentiontoken.org/ to learn more about how the micropayments work.

We look forward to having you join the thousands of domains and YouTube channels already receiving funds from their audience.

**Comment by alexwykoff** [comment]
Suggestions for copy changes are welcome

**Comment by jenn-rhim** [comment]
@alexwykoff  - let's keep the subject line to about 40 characters, including the spaces, which will keep the entirety of the subject to one line without being truncated in the inbox on mobile. 

'... <domain>, verify...' --> do we need the sentence break here instead of comma?

**Comment by ayumi** [comment]
as discussed in Slack:

Let's add a new Publishers API endpoint which will take a domain, which will trigger an email to be sent.
Publishers will determine the email address(es) from WHOIS records.

Eyeshade will call this endpoint when an unverified pub balance goes past a threshold.

See also: Earlier discussion domain WHOIS contact emails: https://github.com/brave-intl/publishers/issues/7

**Comment by nvonpentz** [comment]
In order to minimize the number of unverified publishers in the database, we've decided that the call to action will take the publisher to the signup page where they will begin the verification process from scratch.  So the "Verify My Site" button will take them to the landing/signup page (ie basicattentiontoken.org).

So as it stands there would be 3 links on this email all going to basicattentiontoken.org.  This feels redundant, so I suggest we change:
> Your site has accumulated quite a bit of fundage and we’d love to hand it over.   Please visit https://publishers.basicattentiontoken.org/ to start the verification process. There are no fees, no gimmicks, we just want you to get paid and keep making awesome content.

to
> Your site has accumulated quite a bit of fundage and we’d love to hand it over, but first we need you to verify ownership.  There are no fees, no gimmicks, we just want you to get paid and keep making awesome content.

@alexwykoff @jenn-rhim

**Comment by alexwykoff** [comment]
![domain_cold_call](https://user-images.githubusercontent.com/1434040/34262329-b8ad528c-e631-11e7-818e-a9c0dec21c63.png)

It can certainly work either way. If you keep the link in, it gives two opportunities to get the process started, if you take it out, then we're relying solely on the CTA

**Comment by nvonpentz** [comment]
That's true, but I also think it might be confusing to offer two paths to accomplish the same goal.

For the last bit
> Didn't sign up for this or feel like this email was sent to you by mistake? Feel free to cancel the verification process by Unsubscribing

All publishers who will get this email will have not signed up to receive any emails since we found their information from the WHOIS info on their domain.  Since this is a one off email (and there is no existing Publisher record for them on the rails app), I'm not sure how we could make the Unsubscribe button have any effect without additional communication with eyeshade.

cc @mrose17

**Comment by ayumi** [comment]
i'm curious if "Money..." will go into spam.

we should test it out on staging.
