### ISSUE TITLE
Simplified login for all publishers

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#380]
Changes:
1. remove domain field.
2. email is the only required field (same mechanism as the sign-up: one time use access key will be sent to the user).
3. remove Oauth used for verifying the channel. the same email based login is enforced for the YouTube users. 

![3-log in](https://user-images.githubusercontent.com/4369856/33747668-1338ee5a-db79-11e7-8f0f-9c9964266d63.png)

**Comment by lgebhardt** [comment]
This is in conflict with #274. Are we cancelling OAuth logins?

**Comment by mrose17** [comment]
it's an interim step. we'll implement https://github.com/brave-intl/publishers/issues/274 after this is in production...

**Comment by lgebhardt** [comment]
What should the subject be for the login email? It's currently "[mydomain.com] Brave Publisher login link". Just take out the section in brackets?

**Comment by ayumi** [comment]
@lgebhardt "Brave Publisher login link" sounds good

Personally, I'm very fond of the ability to sign up and log in with a third party provider because it makes trying out new services like Brave Payments very easy.

I'm noting this in case it helps with code planning through the medium future @lgebhardt @dgeb:

With multi-prop, Publishers architecture is in flux, so we might not (re)implement this in the immediate.
However in the medium term we should at least allow account creation via OAuth (perhaps then assigning the OAuth provider account email to the Publishers account wide email). It'd be nice to OAuth login as well, via any one of your properties (And users can use 2FA for added security).

**Comment by dgeb** [comment]
I believe this has been closed by #452
