### ISSUE TITLE
Update font selection

### ISSUE THREAD

**Issue by mixonic** [brave-intl/publishers#464]
According to recent mocks, the dashboard should be using [Poppins](https://fonts.google.com/specimen/Poppins) for headlines and [Muli](https://fonts.google.com/specimen/Muli) for some body text.

Currently the site uses Open Sans. We use 4 variants, and load each font individually from our own servers (not a CDN).

<img width="990" alt="screen shot 2018-01-10 at 1 11 56 pm" src="https://user-images.githubusercontent.com/8752/34795657-e004508e-f607-11e7-99de-bece662d8bbf.png">

We would like to adjust this to improve a) the font for the dashboard and b) the performance of the website.

With those goals in mind, we suggest:

* We use Poppins with weights of 400. This will permit us to use it for headlines.
* We make the "Brave Payments" logo in the header (currently "Open Sans") into an SVG rendered with Poppins 300. This avoids us loading a whole variant (Poppins 300) just for the logo.
* We use Muli 400 and 600 for regular and bold text across the site, as the newer mocks suggest. There are a few places in the mocks where Poppins 300 is used for a label instead of a headline. In those places we will use Muli instead.
* We will load these fonts via Google Fonts instead of as assets from the publisher dashboard domain.
* For the first pass we will *not* change any fonts on the marketing page besides the logo "Brave Payments" font.

These plans are 100% open to feedback.

**Comment by ayumi** [comment]
Can we load fonts from our own servers? It would make me feel marginally better privacy wise.

everything else sounds good to me (cc @jenn-rhim )

**Comment by mixonic** [comment]
@ayumi We should try to shrink the payload regardless of where we host. It would be really, really nice to get these assets behind HTTP2 and/or on a CDN. We can avoid using Google Fonts for the CDN, it simply means a few more hurdles to jump.

**Comment by ayumi** [comment]
@mixonic good thought. Fastly could work as we use it on other Brave properties, as could Cloudfront.

https://publishers.basicattentiontoken.org currently loads 4 fonts, and uncached on a good connection it takes 600 to 1000 ms

using a cdn for fonts might be more of a short/medium term thing (in +1--2 weeks)

**Comment by kpfefferle** [comment]
@jenn-rhim We noticed today that the sketch file we have been using for reference has two different variations of the header nav "Brave Payments" word mark.

One variation uses Open Sans with color `#696B6D`:
![Open Sans](https://user-images.githubusercontent.com/250934/35245980-18079d8a-ff93-11e7-8738-4ace7e5c126d.png)

The other variation uses Poppins with color `#222326 `:
![Poppins](https://user-images.githubusercontent.com/250934/35246025-3da1c8fe-ff93-11e7-8ebf-caa79917a239.png)

We have made the educated guess that we should use the latter Poppins variant for the word mark as headlines elsewhere use Poppins and we had mentioned above that we planned to use SVG for this word mark so that we don't have to load a second weight of the Poppins font.

Can you confirm (or deny) that we made the right choice here?

**Comment by mixonic** [comment]
We're currently using Poppins and Muli. Please call things out that seem wrong as we implement.

I'm going to close this in favor of detailed tickets. Thanks!
