### ISSUE TITLE
Treat log in the same as sign up in the workflow and don't make them go to sign up screen

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#508]
@lgebhardt 

Fundamentally, our log in and sign up processes are the same: a simple email roundtrip. The reason we have them separate on the UI is to support the user's current mental model and accommodate the familiarity. If the user selected log in screen and entered an email that is not in our database, let's just treat it as the sign up request. 

![screen shot 2018-01-22 at 3 38 11 pm](https://user-images.githubusercontent.com/4369856/35250299-cd715e62-ff8a-11e7-976d-a44c3c3db2c4.png)

**Comment by mixonic** [comment]
Per a conversation on Slack: This should be automatically log in a user if their email address cannot be found. Instead it should prompt them in the flash notice with a link to register instead of logging in. For example:

> Email not recognized. Would you like to sign up with the email _email-address@was-not-found.com_ instead?

For reference: https://bravesoftware.slack.com/archives/C6KTLB6G4/p1516741882000199?thread_ts=1516730974.000200&cid=C6KTLB6G4

**Comment by mixonic** [comment]
We actually already kind of do this:

<img width="578" alt="screen shot 2018-01-31 at 1 39 54 pm" src="https://user-images.githubusercontent.com/8752/35648940-45ea6750-068c-11e8-81ab-c68f03087260.png">

I can change the text and make the link actually create the account. Currently it links to the sign up page.
