### ISSUE TITLE
Deposit currency options not present in the dropdown

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#540]
I expected to see other deposit currency options, but currently it's only BAT and not able to change.

**Comment by dgeb** [comment]
It appears that there is a scenario in which only `BAT` is shown: when the wallet has no currencies at all associated with it. This could be caused by a problem with eyeshade (or connecting to eyeshade), since the currencies are retrieved from eyeshade. 

However, I'm testing on staging and currently see multiple currencies:

![screen shot 2018-01-30 at 5 17 15 pm](https://user-images.githubusercontent.com/29122/35594511-78d11e30-05e1-11e8-88fb-789b13473d14.png)

Perhaps @mrose17 fixed this issue in eyeshade. 

@jenn-rhim can you still reproduce?

**Comment by mrose17** [comment]
@dgeb - is this still an issue?

**Comment by dgeb** [comment]
@mrose17 I have not been able to reproduce this issue. I suspect that you resolved this in eyeshade.
