### ISSUE TITLE
Allow wordpress sites to verify using DNS

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#736]
We are currently forcing wordpress sites into using our wordpress plugin which is not working for all users, leaving some sites unverified and without recourse. 

We should add a note somewhere on the wordpress verification page that links to the DNS verification instructions. We did this previously in #359, but have lost the code.

> Not using wordpress, or unable to verify your site with the plugin? **Verify your website by updating your DNS records**

This will provide a path for the many publishers who are having problems with wordpress verification.

/cc @jenn-rhim @LaurenWags

**Comment by jenn-rhim** [comment]
@nvonpentz 

Yes, we should make add this back in, but also the progress train at the top should be clickable so that the user can re-track. 

The only thing I want to mention is, with all the above recourse, the possibility of user considering to switch to a different method (arguably a more difficult one) is probably less likely right after they proceeded, but more after they received the failure notice. When they're given a 'Retry' option, they should be able to get to that step as we're sending them to the Step 1. 

We should add this as one of the suggestions for troubleshooting in the dialog from
https://github.com/brave-intl/publishers/issues/711

Let me know what you think.

**Comment by nvonpentz** [comment]
@jenn-rhim 

#711 will require some new code from eyeshade in addition to all the UI changes.  I don't see it being merged into production in the immediate future, so I created this issue as a short term solution.  That way we have something to tell wordpress publishers who are stuck right now.  We would tell them to remove and re-add their channel then click DNS option.

Making the progress train clickable is a great idea, but it doesn't directly solve this problem, so I think it would be better addressed in #711.
