### ISSUE TITLE
Publishers#home is slow because of synchronous calls to eyeshade

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#838]
We still need to deep dive, but this is a problem that will probably scale poorly:

https://files.slack.com/files-pri/T04PX1BU8-FAK0BM9FT/image.png

Dan brought up a good point that we move the UI portion to use asynchronous javascript. I suggested we could do Redis caching like so:

If Eyeshade stores all the values in Redis:
`REDIS.get("wallet_<id>_balance")`

If we call Eyeshade and then cache the result
```
Rails.cache.fetch("wallet_<id>_balance", expires_in: 24.hours) do
  # Last value should be the value of the wallet balance
  9001
end
```

**Comment by nvonpentz** [comment]
I think we should reduce the total number of calls to get a publisher's wallet and per channel balances to one, then make this call async.  

This way we don't block page load, increase overall response time, and avoid duplicating eyeshade data on publishers (which @evq had some objections to).

We'd have to wait until eyeshade can support doing all of this in one call, though.

cc @dgeb @ayumi

**Comment by dgeb** [comment]
@nvonpentz An async approach sounds good to me. Some data, like channel balances, seems undesirable to cache because a flash of stale content could hurt more than it helps.

> We'd have to wait until eyeshade can support doing all of this in one call, though.

I agree this would be ideal, but I don't think this has to block implementation. If we issue an async call from the dashboard, the request could be fulfilled by any number of sync requests on the backend from publishers to eyeshade. It may take longer than necessary, but at least it wouldn't completely block the display of the dashboard.

**Comment by yachtcaptain23** [comment]
@nvonpentz We can close this right? I forget if this is a N+1 issue.

**Comment by nvonpentz** [comment]
@yachtcaptain23 You created this issue to improve the dashboard page load.

This was partially addressed in #1095 when we switched to using 1 API call for all channel balances instead of 1 API per channel.

However, the wallet is still fetched synchronously in Publishers#home, and that's still a bottleneck.  I plan to remove the synchronous call when we switch to the new dashboard charts.

We should also consider if there is anything we can do to improve the speed of the /wallet endpoint on eyeshade since that takes ~3 seconds.

**Comment by evq** [comment]
@nvonpentz currently the wallet endpoint still involves the pre-transaction table balance calculation. We can remove that, which should help with response time somewhat

**Comment by yachtcaptain23** [comment]
Going to move conversation to https://github.com/brave-intl/publishers/issues/1852 as it has more concise details.
