### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#839]
<strike>We plan on adding an admin dashboard. We'd most likely use one of the following:

(1) Adminstrate
(2) RailsAdmin
(3) ActiveAdmin

I'm leaning more towards RailsAdmin. Ayumi is leaning towards Administrate. @nvonpentz would you research each and scope out integration time and how long it would take to learn?</strike>

Update May 22: Going to use this to track the adding of an admin dashboard. We're going to roll our own admin dashboard.

Features requested:
<strike> - [ ] Suspending users</strike>  https://github.com/brave-intl/publishers/issues/959
<strike> - [ ] Suspending channels</strike> Possibly no business use.
<strike> - [ ] Add notes on users </strike> https://github.com/brave-intl/publishers/issues/959
<strike> - [ ] Override restricted channel verfications </strike> https://github.com/brave-intl/publishers/issues/1005
<strike> - [ ] Resolve channel transfer disputes </strike> https://github.com/brave-intl/publishers/issues/1008
<strike> - [ ] Generate a payout report (unsettled transactions)</strike> https://github.com/brave-intl/publishers/issues/1006
- [x] View any user's statement / balance (settled transations)

**Comment by ayumi** [comment]
Another option is to hand roll a minimal admin UI and use a permissions/ACL library such as https://github.com/CanCanCommunity/cancancan (I have used cancancan it in the past and it works. Also FWIW my previous usage of it has passed a third party security review.)

In any case, due to the powerful nature of admin tools we would need security review. Using a third party library is convenient, but it may also add attack surfaces. Rolling it in-house may be more difficult, but could be easier to audit.

I'd request a security opinion from @flamsmark

**Comment by nvonpentz** [comment]
From #763 (now closed duplicate):

@lgebhardt:
Provide a set of admin and support pages for the publishers site. The full feature set is still TBD. However to support #751 as a starting point the following is needed:

Models:
- Admin: Username and email as well as possibly permissions.

Admin only controllers (accessible only once logged in as an admin):
- UserController: 
   - Manage admin users
- OwnersController:
   - List, show, delete owners

Questions:
- do admins log in with a password, or an email token like publishers
- should 2FA be supported or required for admins
- do we expect to need different levels of admin permissions

@ayumi:
2FA should be required definitely.

All admin and support actions should be logged. The existing audit gem https://github.com/airblade/paper_trail can do that if you set the controller "#whodunnit".

This is a nice authorization gem:
https://github.com/CanCanCommunity/cancancan

for an easy admin panel, administrate looks like it could be good:
https://github.com/thoughtbot/administrate/

**Comment by diracdeltas** [comment]
copying comment from brave-internal since @ayumi is not in that repo:

I have no experience using any of these gems.

at a glance, administrate gets points for having a security reporting process with a pgp key: https://github.com/thoughtbot/administrate/blob/2ff2d614ecade8e5002ae3e967bf7c97e44ef9c8/CONTRIBUTING.md#security. they seem to make an effort at applying patches.

cancan does too, but it's just emailing the current maintainer: https://github.com/CanCanCommunity/cancancan/blob/eb64cb98df0e90db948a7a14b770e423ee171484/CONTRIBUTING.md#reporting-an-issue. it also gets a point for having passed a 3rd party audit according to ayumi.

railsadmin doesn't have a sec reporting process but they list some of their sec issues in https://github.com/sferik/rails_admin/blob/c903d2e1702c6652eaf33ded8fa0892a4f434af1/CHANGELOG.md. same for activeadmin.

i would go with either administrate or cancan due to their having a security process and showing basic signs of caring about security

**Comment by evq** [comment]
2FA should definitely be required for admin roles. I also like the idea of using a IP whitelist for access to admin pages.

**Comment by atsyed87** [comment]
I'd like see an overview of referral statistics too, a solid chunk of support requests have to do with publishers not having accurate stats on their referral links etc. Then again, if we just get the referral stats on the publisher dashboard to update on more regular intervals that would take care of it too.

**Comment by yachtcaptain23** [comment]
Being tracked in several sub-issues.
