### ISSUE TITLE
Possibly lock-down double calls

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#840]
I don't know the source code well enough to make sure we're doing API calls driven by buttons to either internal PUT/POST/DELETE (e.g. database) or to external PUT/POST/DELETE (e.g. Eyeshade or Uphold).

Would you find them and make sure those calls are locked down? Use the `disable_with` for `link_to` and `button_tag` and `data-disable-with` for I believe other HTML attributes like for `input type='submit'`.

**Comment by ayumi** [comment]
pls tag with Research as this issue is kind of vague

**Comment by nvonpentz** [comment]
It looks like [buttons are already disabled after click by default since rails 5](https://github.com/rails/rails/blob/5-0-stable/actionview/CHANGELOG.md#in-order-to-turn-off-missing-key-wrapping).  @yachtcaptain23 noted this is only true for `submit_tags`.  Luckily, nearly all our buttons use submit tags, and disable by default.  I only looked for `link_to` and `button_tags` that might modify state or initiate an external http request.

We do not use `button_tag` or `button_to` anywhere in the code.

I found that we are using `link_to` for uphold connection and disconnection:
https://github.com/brave-intl/publishers/blob/a9961ed1b7f36f0e2b059e1e579a15f01876dc03/app/views/publishers/home.html.slim#L81

https://github.com/brave-intl/publishers/blob/a9961ed1b7f36f0e2b059e1e579a15f01876dc03/app/views/publishers/home.html.slim#L92

And that a publisher download’s their statement via a `link_to`
https://github.com/brave-intl/publishers/blob/a9961ed1b7f36f0e2b059e1e579a15f01876dc03/app/views/publishers/home.html.slim#L123

Since #786 rewrites this code, these edits will be blocked until it has been resolved.

**Comment by yachtcaptain23** [comment]
Didn't realize this was the default behavior as part of Rails 5.

Closing.
