### ISSUE TITLE
Publisher Status

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#850]
Before we implement `status` on publishers, I want to make sure we get the states down correctly:

`created` as opposed to `create`
`onboarding` as opposed to `updating`
`active` 
`suspended`
`deleted` which is just `archived`

@nvonpentz let me know if you agree or disagree.

**Comment by nvonpentz** [comment]
To go from `onboarding` to `active`, a publisher would need to verify their email address, agree to the TOS, and address the 2fa prompt, right?

I think we we'll need to permanently delete to stay GDPR compliant.

**Comment by nvonpentz** [comment]
This is the plan:

Create a new table `PublisherStatusUpdate`. A publisher will have many `PublisherStatusUpdates`.  When an event triggers a change in publisher status, we create a new `PublisherStatusUpdate` with that status.

At a minimum, the new table should have a `created_at`, `status`, and `publisher` column.  The `status` column will be a string, either `created`, `onboarding`, `active`, `suspended`, or `deleted`.  For now, we will only support `created` (non email verified publishers), `onboarding` (email verified publishers that have yet to complete both (1) agreeing to TOS and (2) addressing the 2fa prompt), and `active` (everyone else).  `suspended` and `deleted` will come later as we gain that functionality.

We will create a method on the publisher model that will get the most recently `PublisherStatusUpdate` for a publisher by selecting the one with the most recent `created_at`.

@yachtcaptain23 Is this the right approach?  Are there any other columns you'd like to add to the `PublisherStatusUpdate` table?

**Comment by nvonpentz** [comment]
If we try to fill in the status for existing publishers, we can only be certain that we mark those in in `created` phase correctly. 

These publishers could be marked as `created`
```ruby
Publisher.where(email: nil)
```
Since `two_factor_prompted_at` and `agreed_to_tos` were later additions, some publishers do not have values here when you might expect them to.  A publisher could have agreed to the terms of service prior to when we started recording that information in the db.  Because of this we won't be able to accurately mark existing publisher status as `onboarding` and `active`. 

We can assume that any publisher that has a channel is in the active phase, and could mark them as `active`, though it would not cover all the potential `active` publishers.
