### ISSUE TITLE
Suspend features

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#963]
This issue will track all the features for `suspend` and state transitions to and from `suspend`.

- [x] Don't allow user to login.
- [x] Potentially send email notifying suspension

**Comment by mandar-brave** [comment]
- 100% of the users should be prevented from being logged in.
- a banner needs to be shown to the user with a message " Your account is temporarily suspended due to suspicious activity being detected, please <hyperlink> email </hyerplink> if you want to discuss your account"
- once conversation with the customer support (Asad, Mandar, Nick), we can decide if account moves to "active" state or if can be permanently deleted

If owner is deleted, all properties need to move back to the Pub App and continue collecting contributions, grants, etc.
If owner is moved to active, account is set to default reputation.

@yachtcaptain23 -- let me know if this can get you started; i need to work with @jenn-rhim for the step-2 (banner) part

**Comment by yachtcaptain23** [comment]
Related to https://github.com/brave-intl/publishers/pull/999

**Comment by yachtcaptain23** [comment]
Emails sent
